= money eXCHange coin
Peter Lawrey

The eXCHange coin is designed to support high velocity financial transactions for

- payments
- exchange of one currency for another
- fixed income or discounts on slow money
- virtualised currencies
- storage and retrieval of transaction history

Each of these markets process trillions per day.

Transactions are localised by;

- general region for payments
- currency for foreign exchange

to speed up transactions in that location.
Transactions between localisations,
are federated to supports transaction globally.

== Currency movement

The currency has three broad objectives

- utility across financial services
- stability
- transaction use consumes coins, providing an upward pressure on value.

=== Currency Utility

The eXCHange coin is look to support a number of segments
and be an interchangeable coin between them.
In some ways, they will be like existing coins which specialise in particular types of transactions.

- payments (Bitcoin)
- foreign exchange (Ripple)
- a platform for building new services (Etherium)
- transaction storage and retrieval (filecoin)

As coins are designed to be deflationary, they all can provide a return,
however the eXCHange coin would be designed to explicitly support "slow money"
where account holders can buy money at a discount provided it is held
for a short period of time.

== Federated stake holders

To improve throughput and reduce latency, these systems will be divided into regions in a federated model.

=== Multiple independent regions

Some regions will be predefined, such as Europe, Central Asia, or South America.
Transactions within a region are agreed there and don't need to be shared globally.
This reduces time to consensus, as well as increasing scalability.

When a transaction is across regions, only those two regions are involved.
If someone in Brazil wants to send money to China, only those regions are involved.

== Central bank

There are number of functions that a central bank usually performs to improve
the stability and quality of a coin. However, in a decentralised model all the stake holders
participate in setting

- fees for international payments
- the opening price and number of new issues coins
- the limit on reserved coins
- issuing future coins

=== Money fragmentation and limiting supply

As coins are divided again and again they become of smaller value and more numerous. They never the less use the same capacity in terms of bytes placing ever increasing strain on bandwidth and storage.

Also if the supply of coins is too high, this reduces it's value leading to inflation.

To solve both of these issues, the number of coins, both current and those for future issue, held by the central bank will be limited
with the smallest coins being destroyed first.

There will be a special transfer to void to destroy coins.

=== Slow money

Each coin is dated with a year from which it is usable.
Coins issued for future years can be bought on a dedicated global market
at a discount. As they approach the year for issue, they approach parity
and ultimately become a regular coin.

There could also be restrictions on how quickly these coins can be resold.

e.g. a 2019 1K coin might be bought for 930 coins at the start of 2018,
and a 2020 1K coin might be bought for 845 coins.

== Currency stabilisation

A currency needs to take stability for people to feel comfortable holding it for any length of time.
To improve stability a number of measures are proposed.

==== Upward pressure

Crypto-currencies are know for their deflationary characteristics

- limiting how many coins are held in reserve and destroying.
- buying back a limited number coins if the coins drops below 3% of the weekly open.
- coins are consumed as fees.

==== Ways to avoid currency stavation

If the number of coins are too long, or the fragmentation is too high, this could cause a loss of confience in the future of the tokens.

- Support coins rolled out in future years, e.g. 2019, 2020, 2021 in a limited manner so stakeholders can see the extent of the money supply.
- allow stakeholders who risk losing money if the market falls, to make the same amount if it rises (and *only* if it rises by a predetermined amount)

=== Market Stake Holders

In each weekly cycle, stake holders can put forward tokens as security which gives them

- proportional voting rights, on fees and stability measures.
- acts as a buffer when the market falls.
- is an euqal opportunity to make money should the market rise.

For example, say we have 50 market stake holders each putting an average of $1000 for the XCH/USD market.

In the week before the cycle, stake holders agree by weighted concensus,

- the point at which stability measures apply .e.g a 2.5% rise or fall.
- the transaction fee, per transaction, per byte, as a percentage of value.

Once the stake holders are agreed, the measures and the fees have reached concensus, in the following week;

- stake holders offer to buy at the weekly openning price minus the stability percentage e.g. 2.5%
- they can sell new XCH at 2.5% above the openning, up to the size of their stake.

NOTE: The can only sell new coins up to the value of their stake if the market goes up significantly, and they can lose an equal amount of money if it falls.

This is intended to be a zero-sum-gain except stake holders also get a share of the fees, in proportion to their stake.

